### ISSUE TITLE
建议添加更多的专业化的性能指标

### ISSUE THREAD

**Issue by kushao1267** [yunsonbai/ysab#2]
例如支持:
1.TP99、TP99、TP9999的指标
2.支持用户自定义服务的SLA 指标，例如最低可接受的响应迟延，测试中请求的达标率

(平均时延、最大最小时延在业界几乎没啥参考价值)

**Comment by yunsonbai** [comment]
@kushao1267 非常感谢您的意见，目前加上了TP指标。
